### ISSUE TITLE
Message for iamqiz unrelated to this project

### ISSUE THREAD

**Issue by cniggeler** [iamqiz/awesome-stars-copy#2]
Since Github doesn't offer DM and usoft closed the case, I had one key note for iamqiz RE: Re: [microsoft/terminal] STILL Can't bypass DOSkey macro with leading space (Issue #16875):

@iamqiz Your ver command output looks like you're on Windows 10, is that correct? I was told in a different issue ID (same problem, just "merged") that they weren't going to retrofit the fix to Win 10.

**Comment by iamqiz** [comment]
yes .my  os  is win10;
it is crazy that they do not plan to fix it in win10 which many users still use 😲

**Comment by iamqiz** [comment]
@cniggeler are you using win11? i do not plan to use it within 3 years😅 because i encounter a problem in win11 before

**Comment by cniggeler** [comment]
@iamqiz Yes I am now on Win 11. My Win10 workstation was starting to act up, so I got a new machine and bit the bullet with Win11 late last year. Overall, I don't see a lot of difference between it and Win10 but rather the continuation of the trend since Win8 of "apps" and ads.
